// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-jCcROgu4Q0ZfL8NSI0Uu5OCNV-nG4o0',
    appId: '1:753114563700:web:c4680040a9cef1ff623d21',
    messagingSenderId: '753114563700',
    projectId: 'application-63412',
    authDomain: 'application-63412.firebaseapp.com',
    storageBucket: 'application-63412.firebasestorage.app',
    measurementId: 'G-L4DB8D4EBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPG5HJXIecS1NZQznkO5JUwZYrR2QvmTE',
    appId: '1:753114563700:android:3bee320917df913a623d21',
    messagingSenderId: '753114563700',
    projectId: 'application-63412',
    storageBucket: 'application-63412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq14fRUa3xXFBX63EU-2zlThOTetOhLs4',
    appId: '1:753114563700:ios:9b95ce7cc00bdd15623d21',
    messagingSenderId: '753114563700',
    projectId: 'application-63412',
    storageBucket: 'application-63412.firebasestorage.app',
    iosClientId: '753114563700-er38m6g56mjk1o9i4a8spv18rhhkkqvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq14fRUa3xXFBX63EU-2zlThOTetOhLs4',
    appId: '1:753114563700:ios:9b95ce7cc00bdd15623d21',
    messagingSenderId: '753114563700',
    projectId: 'application-63412',
    storageBucket: 'application-63412.firebasestorage.app',
    iosClientId: '753114563700-er38m6g56mjk1o9i4a8spv18rhhkkqvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-jCcROgu4Q0ZfL8NSI0Uu5OCNV-nG4o0',
    appId: '1:753114563700:web:9eda380994f43319623d21',
    messagingSenderId: '753114563700',
    projectId: 'application-63412',
    authDomain: 'application-63412.firebaseapp.com',
    storageBucket: 'application-63412.firebasestorage.app',
    measurementId: 'G-4NTQ3G15NV',
  );

}