name: healthy_food

description: A healthy food application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  fl_chart: ^1.0.0

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^7.1.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.1
  cloud_firestore: ^5.6.8
  image_picker: ^1.0.4
  intl: ^0.20.2
  firebase_storage: ^12.4.6
  lottie: ^3.3.1
  firebase_app_check: ^0.3.2+6
  uuid: ^4.0.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
